language: php

jobs:
    include:
        - name: 'Tests under PHP 7.4'
          php: '7.4'
          dist: bionic
        - name: 'Tests under PHP 8.0'
          php: '8.0'
          dist: bionic
        - name: 'Tests under PHP nightly'
          php: 'nightly'
          dist: bionic

    fast_finish: true
    allow_failures:
        - php: 'nightly'

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer install

script:
    - php -dmemory_limit=-1 -dxdebug.mode=coverage ./vendor/phpunit/phpunit/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php -dmemory_limit=-1 ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_success:
    - bash <(curl -s https://codecov.io/bash)
